// IPC channel name constants, shared between main and renderer processes
export const IPC_CHANNELS = {
  APP_GET_VERSION: 'app:get-version',
  FILE_OPEN: 'file:open',
  FILE_CREATE: 'file:create',
  FILE_OPEN_FOLDER: 'file:open-folder',
  FILE_LIST_WORKSPACE_FILES: 'file:list-workspace-files',
  FILE_READ: 'file:read',
  FILE_READ_STREAM: 'file:read-stream',
  FILE_INFO: 'file:info',
  FILE_WRITE: 'file:write',
  SETTINGS_SAVE: 'settings:save',
  SETTINGS_GET: 'settings:get',
  SETTINGS_GET_CATALOG: 'settings:get-catalog',
  SETTINGS_TEST_CONNECTION: 'settings:test-connection',
  SETTINGS_WORKSPACE_VERIFY: 'settings:workspace-verify',
  AGENT_SEND: 'agent:send',
  AGENT_CANCEL: 'agent:cancel',
  AGENT_STREAM: 'agent:stream',
  SKILL_IMPORT: 'skill:import',
  SKILL_IMPORT_FOLDER: 'skill:import-folder',
  SKILL_LIST: 'skill:list',
  SKILL_GET: 'skill:get',
  SKILL_SAVE: 'skill:save',
  SKILL_TOGGLE: 'skill:toggle',
  SKILL_DELETE: 'skill:delete',
  EDITOR_JUMP_TO_LINE: 'editor:jump-to-line',
  EDITOR_PREVIEW_CHANGE: 'editor:preview-change',
  EDITOR_APPLY_CHANGE: 'editor:apply-change',
  EDITOR_REJECT_CHANGE: 'editor:reject-change',
  EDITOR_APPLY_TRANSACTION: 'editor:apply-transaction',
  EDITOR_REJECT_TRANSACTION: 'editor:reject-transaction',
  EDITOR_CHANGE_APPLIED: 'editor:change-applied',
  CHAT_QUOTE_TEXT: 'chat:quote-text',
  EXPORT_REPORT: 'export:report',
} as const;
